import React, { useState, useEffect } from "react";
import { Shield, Check, AlertTriangle, Scale, Lock, ExternalLink, HelpCircle } from "lucide-react";

interface ComplianceDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  requireAcceptance?: boolean;
  onAccept?: () => void;
}

export default function ComplianceDrawer({ 
  isOpen, 
  onClose, 
  requireAcceptance = false, 
  onAccept 
}: ComplianceDrawerProps) {
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const [acceptedTerms, setAcceptedTerms] = useState(false);
  const scrollRef = React.useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      setHasScrolledToBottom(false);
      // If it's a short window or already viewed
      const element = scrollRef.current;
      if (element) {
        element.scrollTop = 0;
      }
    }
  }, [isOpen]);

  const handleScroll = () => {
    const element = scrollRef.current;
    if (element) {
      const isBottom = Math.abs(element.scrollHeight - element.clientHeight - element.scrollTop) < 10;
      if (isBottom) {
        setHasScrolledToBottom(true);
      }
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 md:p-6 overflow-y-auto">
      <div className="relative bg-[#0c0c0c] border border-white/20 w-full max-w-3xl rounded-none shadow-2xl flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="p-5 border-b border-white/10 flex items-center justify-between bg-black/60">
          <div className="flex items-center gap-2">
            <Shield size={18} className="text-[#7C3AED] animate-pulse" />
            <div>
              <h3 className="text-sm font-black uppercase tracking-widest text-white">
                REGULATORY COMPLIANCE & LEGAL DISCLAIMERS
              </h3>
              <span className="text-[9px] font-mono text-[#F472B6]">SEC-GUARD v3 // MASTER DEFENSE PROTOCOL</span>
            </div>
          </div>
          {!requireAcceptance && (
            <button 
              onClick={onClose}
              className="text-xs text-white/40 hover:text-white uppercase font-mono tracking-widest px-3 py-1 bg-white/5 border border-white/10"
            >
              Close [ESC]
            </button>
          )}
        </div>

        {/* Scrollable Disclaimer Content */}
        <div 
          ref={scrollRef}
          onScroll={handleScroll}
          className="flex-1 overflow-y-auto p-6 space-y-6 text-xs text-white/70 leading-relaxed font-sans scrollbar-thin scrollbar-thumb-white/10"
        >
          {/* Quick Notice Banner */}
          <div className="p-4 bg-[#7C3AED]/10 border border-[#7C3AED]/30 text-white space-y-1.5 rounded-none flex gap-3">
            <AlertTriangle className="text-[#7C3AED] shrink-0 mt-0.5" size={16} />
            <div>
              <p className="font-bold uppercase text-[10px] tracking-wider text-white">Sovereign Regulatory Safe Harbor</p>
              <p className="text-[10px] text-white/70">
                YouChain operates as a non-custodial decentralized application mapping custom Clarity smart contracts on Bitcoin L2 (Stacks). By interacting with the protocol, you acknowledge and agree to the mathematical constraints and legal liability disclaimers herein.
              </p>
            </div>
          </div>

          {/* Section 6.1 */}
          <div className="space-y-3">
            <h4 className="font-black text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-white/5 pb-1 font-mono text-[11px]">
              <span className="text-[#7C3AED]">6.1</span> FINANCIAL & TRANSACTIONAL DISCLAIMERS
            </h4>
            <p className="text-white/50 font-mono text-[10px] leading-relaxed">
              All educational modules, trading logs, investment frameworks, and system blueprints—including but not limited to the Keystone Bitcoin Strategy, 24-Hour Alpha Stratagem, and algorithmic models—are provided strictly for educational, informational, and illustrative purposes.
            </p>
            <ul className="space-y-2.5 pl-2 border-l border-white/10">
              <li>
                <strong className="text-white uppercase text-[10px] block">No Professional Advice:</strong>
                <span className="text-white/60">The Founder and the Firm do not operate as registered financial advisors, commodity trading advisors, broker-dealers, or investment analysts under any jurisdiction. No information generated by the system constitutes a solicitation, recommendation, or endorsement to buy or sell securities, digital assets, or financial instruments.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">AVGO Validation & Historical Data:</strong>
                <span className="text-white/60">Any reference to previous successful market executions, including the AVGO strategy, is used solely to demonstrate system logic, loss avoidance, and adherence to the "Protective Stop." Past performance of any algorithm, protective stop, or historical trade is not indicative of future market results.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">Risk of Loss and Volatility:</strong>
                <span className="text-white/60">Trading equities and volatile cryptocurrencies carries a substantial risk of financial loss. Users execute trades entirely at their own discretion and financial risk. The "Unbreakable System" focuses on process discipline and capital preservation, not on predicting market cycles or guaranteeing returns.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">The Spouse Protocol:</strong>
                <span className="text-white/60">The "Investment Trade Log" (ITL) and its mandatory reporting structure under the "Spouse Protocol" serve as internal accountability benchmarks to prevent emotional over-leveraging and maintain family-level check-and-balance systems.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">Mandatory Affiliate Disclosure:</strong>
                <span className="text-white/60">Users must be explicitly notified that the system features referral and affiliate links to cryptocurrency exchange platforms (e.g., KuCoin, Binance) to offset payment processing costs.</span>
              </li>
            </ul>
          </div>

          {/* Section 6.2 */}
          <div className="space-y-3">
            <h4 className="font-black text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-white/5 pb-1 font-mono text-[11px]">
              <span className="text-[#7C3AED]">6.2</span> WEB3 & DECENTRALIZED PROTOCOL DISCLAIMER (THE "YOUCHAIN" PLATFORM)
            </h4>
            <p className="text-white/50 font-mono text-[10px] leading-relaxed">
              The YouChain platform operates utilizing decentralized, peer-to-peer Web3 protocols, public smart contracts (Clarity/Stacks L2), and decentralized storage systems (Arweave/IPFS).
            </p>
            <ul className="space-y-2.5 pl-2 border-l border-white/10">
              <li>
                <strong className="text-white uppercase text-[10px] block">Non-Custodial Architecture:</strong>
                <span className="text-white/60">YouChain is a non-custodial protocol. The Founder and Firm do not hold, manage, or have access to users' private keys, seed phrases, or digital wallets. All logins are managed via cryptographic multi-chain signatures (Stacks / BIP-322) validated via custom Firebase JSON Web Tokens (JWT).</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">Clarity Smart Contracts (SIP-009):</strong>
                <span className="text-white/60">The platform maps video registrations, licensing, and automatic royalty splits using Clarity smart contracts settled directly on the Bitcoin L1 blockchain. All on-chain transfers are subject to user-approved "post-conditions" to prevent unauthorized asset draining.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">Lazy Minting Economics:</strong>
                <span className="text-white/60">To eliminate upfront costs for creators, the platform supports off-chain cryptographic metadata signatures, shifting gas costs to the purchaser at the point of sale. No warranty is made regarding the gas fee stability, which is calculated strictly based on: Gas Cost = Gas Units Used * Current Gas Price.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">No Guarantee of Yield:</strong>
                <span className="text-white/60">Fractional licensing, lazy minting, and IP-licensing monetization structures (via Story Protocol integrations) are software tools. The system does not guarantee any level of sales, royalties, or recurring passive income. No liability is assumed for network failures on Stacks L2, Bitcoin L1, or external RPC nodes.</span>
              </li>
            </ul>
          </div>

          {/* Section 6.16 */}
          <div className="space-y-3">
            <h4 className="font-black text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-white/5 pb-1 font-mono text-[11px]">
              <span className="text-[#7C3AED]">6.16</span> SEC COMPLIANCE GUARD, NON-SECURITY WARRANTY, AND SOVEREIGN CONTRACTUAL SAFE HARBOR (THE "SEC/SCC GUARD")
            </h4>
            <p className="text-white/50 font-mono text-[10px] leading-relaxed">
              This Section forms an absolute structural shield protecting the native blockchain mechanics, tokenized transactions, smart contract logic, and game loop elements of this partnership from classification as investment contracts, securities, or regulated financial instruments under international and domestic regulatory guidelines (including but not limited to the United States SEC Howey Test parameters).
            </p>
            <ul className="space-y-2.5 pl-2 border-l border-white/10 font-sans">
              <li>
                <strong className="text-white uppercase text-[10px] block">No Intent to Create a Security:</strong>
                <span className="text-white/60">The parties covenant and agree that all utility tokens, NFTs, Clarity smart contracts (including SIP-009 video assets), on-chain routing scripts, and computational allocation rules (including the 10% Omega Yield Tithe) are software tools designed exclusively for functional utility, decentralization, in-game logic, and digital rights registration. They do not represent, nor are they intended to represent, ownership shares, debt instruments, capital stock, or equity options in any corporate entity.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">Explicit Satisfaction of the Howey Test Defense Parameters:</strong>
                <ul className="space-y-1.5 pl-3 list-disc text-white/50 text-[10px] mt-1">
                  <li><span className="text-white font-semibold">No Investment of Money:</span> Any acquisition of digital items, play tokens, or NFTs within the ZOS-CORE or YouChain ecosystems represents a direct commercial trade of capital for immediate software utility, creative art, or programmatic execution. No capital is pooled for the purpose of joint enterprise asset growth.</li>
                  <li><span className="text-white font-semibold">No Common Enterprise:</span> The architecture operates via peer-to-peer, non-custodial smart contracts settling on Stacks L2 and Bitcoin L1. The operational structure is designed for sovereign execution where the Founder and the Firm do not run a centralized common enterprise.</li>
                  <li><span className="text-white font-semibold">Zero Expectation of Profit Driven by Others:</span> Any potential financial optimization achieved by an end-user is derived strictly from their own independent labor, trade execution, and mathematical adherence to the "Protective Stop" protocols. The system's value is entirely native to its structural discipline, not the managerial or developmental efforts of the Founder or Partner.</li>
                </ul>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">Smart Contract Code ("SCC") Autonomy Warranty:</strong>
                <span className="text-white/60">The Partner acknowledges that the Clarity smart contracts deployed on Stacks L2 are self-executing, final, and immutable. No legal or regulatory action initiated against the Founder or the Partner can alter, stop, or reverse the code's automated execution path once verified on-chain. The code is the law of the land, and the parties assume zero liability for the autonomous actions of public mainnet protocols.</span>
              </li>
              <li>
                <strong className="text-white uppercase text-[10px] block">Indemnification for Sovereign Regulatory Actions:</strong>
                <span className="text-white/60">The Partner agrees to defend, indemnify, and hold harmless the Founder (Genesis Z) and his personal estate against any and all regulatory inquiries, cease-and-desist mandates, civil litigation, or enforcement actions initiated by securities commissions or monetary authorities (such as the SEC, CFTC, or FinCEN) resulting from the Partner's marketing, onboarding, or distribution of these digital products.</span>
              </li>
            </ul>
          </div>

          <div className="pt-4 border-t border-white/5 text-center text-[10px] text-white/40 font-mono">
            SEC-GUARD v3 SHIELD ENFORCED BY SOVEREIGN WRITER PRINCIPAL (GENESIS Z)
          </div>
        </div>

        {/* Footer Accept zone */}
        <div className="p-5 border-t border-white/10 bg-black/80 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          {requireAcceptance ? (
            <>
              <label className="flex items-center gap-2.5 cursor-pointer text-xs select-none">
                <input 
                  type="checkbox" 
                  checked={acceptedTerms}
                  onChange={(e) => setAcceptedTerms(e.target.checked)}
                  className="rounded-none border-white/20 text-[#7C3AED] focus:ring-0 focus:ring-offset-0 cursor-pointer h-4 w-4"
                />
                <span className="text-white/80 font-mono text-[10px] uppercase">
                  I accept the Master Systems and Compliance Disclaimers.
                </span>
              </label>
              <button
                type="button"
                onClick={() => {
                  if (acceptedTerms && onAccept) {
                    onAccept();
                  }
                }}
                disabled={!acceptedTerms}
                className="py-2.5 px-6 bg-white text-black disabled:bg-white/10 disabled:text-white/30 uppercase text-xs font-black tracking-widest rounded-none transition-all cursor-pointer flex items-center justify-center gap-1"
              >
                <span>Initialize Ecosystem</span>
                <Check size={14} />
              </button>
            </>
          ) : (
            <div className="w-full flex justify-end">
              <button
                type="button"
                onClick={onClose}
                className="py-2.5 px-6 bg-[#7C3AED] hover:bg-[#6D28D9] text-white uppercase text-xs font-black tracking-widest rounded-none transition-all cursor-pointer"
              >
                Acknowledge Disclaimers
              </button>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
